### PR TITLE
Amiceli feature/allow user register

### PR DESCRIPTION
**Pull request by devimust**

### CODE REVIEW

**Comment by devimust** [comment]
@amiceli please take a look at the changes before I merge.

**Comment by amiceli** [comment]
ok I'll check it asap.

**Comment by amiceli** [comment]
@devimust Thanks for your work . I've noted your modification for my feature code.

**Comment by devimust** [comment]
Cool, should I merge my branch?

On 29/11/2016 11:49 AM, "MICELI Antoine" <notifications@github.com> wrote:
>
> @devimust Thanks for your work . I've noted your modification for my
feature code.

**Comment by amiceli** [comment]
I think you can merge it.

**Pull request merged**
